# Generated by Django 5.1.3 on 2024-12-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='enter your first name here', max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20, verbose_name='surname')),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
